### ISSUE TITLE
Project name conflict

### ISSUE THREAD

**Issue by Superpat** [chigix/mandoc#1]
Hi!

Seeing as this project is still pretty young, I was wondering if you were aware of the [mandoc](https://mandoc.bsd.lv) project? The name conflict is not a problem per se, as many projects coexist with similar names, but just in case you had not heard of it before, I thought I'd share the info.

I am not affiliated with the project in any way though, just fell on this while reading up on the former.

**Comment by chigix** [comment]
Hi @Superpat , Thanks for creating this issue contributing to the problem of unclear readme document lacking the sections like purposes or vision for this project.

Actually, not only this project name conflict, the job and the object of this project is to provide an alternate approach, as well, to the ancient mandoc project and [pandoc](http://pandoc.org/) project that I am actually using every day when coping with assignments and reports at university. 

One big reason for creating this project is that I want to use javascript(Actually, TypeScript) and have a javascript-friendly document compiling library or tool, which could be loaded or required through nodejs directly without any dependency on systems, platforms or migration between other communitites.

For sure, more exact naming like `ManDoc.js` is also in plan building the home page for this project, which is still not finished and could be viewed from the `docs-app` branch.

Apologize for the lack of introduce which should be mentioned in documents again, as you said this project exactly started very new, where I'm now still struggling with the concept improvement and implement to satisfy basic usages and daily practices.

Issues and Bug Reports, however, are welcome~~
